### ISSUE TITLE
Minimap pet tooltips add lines endlessly

### ISSUE THREAD

**Issue by ckaotik** [Phanx/BetterBattlePetTooltip#3]
This is triggered just by hovering a battle pet minimap blop and only when showing the number of collected pets for this species.

See attached screenshot.
![bildschirmfoto 2014-12-23 um 12 14 50](https://cloud.githubusercontent.com/assets/151904/5537181/58f48bb4-8a9d-11e4-90e5-06ec46976f11.png)

Edit: Using version 6.0.3.20 from Curse client

**Comment by Mr-Cake** [comment]
Hi, hopefully you see this. Just installed your addon and got this issue, using latest version off curse. Looks different to ckaotik's though http://puu.sh/gJskB/3a8613e907.png
