### ISSUE TITLE
Error - can't concatenate "nil" value breed

### ISSUE THREAD

**Issue by vvv444** [Phanx/BetterBattlePetTooltip#7]
Addon version 6.2.0.25
Game version 6.2.2.20490 (x64)

**Reproduction scenario**
1. Run the game.
2. Find wild pet that you don't have in your collection.
3. Enter pet battle. Surrender.
4. When the pet reappears, mouse-over it.
5. Bang, we get an error in Core.lua line 372, can't concatenate nil value.

**Fix that worked for me**
Replace this line from
`infoString = breed .. PetQualityStrings[quality]`
to
`infoString = (breed or "") .. PetQualityStrings[quality]`

**Comment by Phanx** [comment]
Same as #8 ... yours is a better report, but theirs had the line number for the current codebase. Fixed.
